./projectrunscript SPEC bzip2 LFU
./projectrunscript SPEC bzip2 SRRIP
./projectrunscript SPEC gcc LFU
./projectrunscript SPEC gcc SRRIP
./projectrunscript SPEC mcf LFU
./projectrunscript SPEC mcf SRRIP
./projectrunscript SPEC hmmer LFU
./projectrunscript SPEC hmmer SRRIP
./projectrunscript SPEC sjeng LFU
./projectrunscript SPEC sjeng SRRIP
./projectrunscript SPEC libquantum LFU
./projectrunscript SPEC libquantum SRRIP
./projectrunscript SPEC xalan LFU
./projectrunscript SPEC xalan SRRIP
./projectrunscript SPEC milc LFU
./projectrunscript SPEC milc SRRIP
./projectrunscript SPEC cactusADM LFU
./projectrunscript SPEC cactusADM SRRIP
./projectrunscript SPEC leslie3d LFU
./projectrunscript SPEC leslie3d SRRIP
./projectrunscript SPEC namd LFU
./projectrunscript SPEC namd SRRIP
./projectrunscript SPEC soplex LFU
./projectrunscript SPEC soplex SRRIP
./projectrunscript SPEC calculix LFU
./projectrunscript SPEC calculix SRRIP
./projectrunscript SPEC lbm LFU
./projectrunscript SPEC lbm SRRIP
